### ISSUE TITLE
Feedback form overflow

### ISSUE THREAD

**Issue by elliott-king** [bbedevian/jtme#12]
If both the "new Job" and "feedback" forms are opened, the sidebar goes off the bottom of the page & I can't see the submit button. I went through the CSS and can't for the life of me figure out how to fix this.

![Screen Shot 2020-11-18 at 8 07 31 AM](https://user-images.githubusercontent.com/8884571/99534384-54781380-2975-11eb-83f2-5a84a74d8fb6.png)

**Comment by imjoshellis** [comment]
I took a look at this, and I see the issue. I'll hop in the code and submit a PR.
