### ISSUE TITLE
Can't scroll on home page when both dropdowns are open

### ISSUE THREAD

**Issue by jasminnancy** [bbedevian/jtme#15]
**Specs**
Browser: Google Chrome
Screen Size: 13"

**To Replicate**
Go to home page
Open both the `Add a new Job` and `Give us feedback` dropdowns.
Cannot scroll down to submit feedback.

**Comment by imjoshellis** [comment]
#16 addresses this

**Comment by MisterRK** [comment]
Fixed with only one form allowed to be open at a time
